### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by waleeg** [fritzlabs/fritz-examples#22]
Hi there,

I am curious about the example project. 
Any chance to recompile your framework with the Swift 5.1 compiler?

Thanks.

**Comment by ghop02** [comment]
Hi! We are about to release an update to this repository that will include more examples, can you try building off of the version of the Fritz AI Studio in this pr? https://github.com/fritzlabs/heartbeat-ios/pull/21

**Comment by iMemento** [comment]
Same error, how to fix it ?

**Comment by jamesonthecrow** [comment]
Fritz version 4.1.2 and higher is compatible with Swift 5.1 and Xcode 10.3. These demos in this repository should be updated to use the latest version, but you can always change the podfile to upgrade explicitly. We have also added instructions for fixing things to our FAQ page on the docs:

https://docs.fritz.ai/faq.html#swift-version-compiler-errors
