### ISSUE TITLE
Unity samples crash on Android

### ISSUE THREAD

**Issue by ShacharWeis** [fritzlabs/fritz-examples#25]
I tried both Unity samples on Android and they both crash.

`cameraManager.TryGetLatestImage(out image)` always returns false. 

There is an object in the scene called `GameObject` with a missing script. That script may or may not be important, I have no idea.

**Comment by hsiaoer** [comment]
Hi @ShacharWeis 

Can you provide me with a little more information?
- What device / Android version are you running this on?
- What version of Unity are you using?
- Can you check that under "Unity Package Manager", ARFoundation and ARCore XR are installed
- Does the app crash on startup? If so, can you send me the error logs?

Thanks,
Eric

**Comment by murtaza98** [comment]
I was facing the same issue.
The solution is to add an API key which u get from the Fritz website in the Project Settings.
