### ISSUE TITLE
Failed to load module 'Fritz'

### ISSUE THREAD

**Issue by FlorolF1** [fritzlabs/fritz-examples#34]
Hey,

i am using Fritz for a while now. Within my own apps i am using Fritz Version 3.x. Its working fine.
Now i am trying to update to a newer version 5.0.5 .
I am getting the error : Failed to load module 'Fritz' and tons of other errors.
This happens in all demo apps from fritz, and within my own apps.

Any idea how to fix this?

Xcode 11, Swift 5.1 , os 10.15
![Bildschirmfoto 2019-11-29 um 10 07 46 (2)](https://user-images.githubusercontent.com/29608141/69857449-4e82b180-1290-11ea-8937-34851bfe6ca7.png)

**Comment by ghop02** [comment]
Hi @FlorolF1 , sorry about this.  I've seen a few people with this error now and haven't been able to reproduce it locally.

What version of Xcode 11 are you using?

**Comment by SergeyDivak** [comment]
Same errors for me also can not build demo (
xcode Version 11.1 (11A1027)

Failed to load module 'Fritz'

**Comment by ghop02** [comment]
Is it possible to upgrade xcode? Sorry for this inconvenience, more curious if it fixes it (I don't see an easy way to downgrade xcode myself)

**Comment by SergeyDivak** [comment]
Hi, updated xcode yes all errors gone, but i see only one error 

Cannot invoke initializer for type 'FritzVisionPeopleSegmentationModelFast' with no arguments
private lazy var visionModel = FritzVisionPeopleSegmentationModelFast()

it seems FritzVisionPeopleSegmentationModelFast constructor required object
Could you please assist?

I try use  pod 'Fritz/VisionSegmentationModel/People/Accurate'

**Comment by SergeyDivak** [comment]
Hi thanks. I updated xcode to latest version all errors gone. 
I try use FritzVisionPeopleSegmentationModelAccurate()
added in pod  pod 'Fritz/VisionSegmentationModel/People/Accurate'

All build fine but i got error in runtime
Thread 1: Fatal error: Please download the Fritz-Info.plist  

For demo project fritz/fritz-examples/iOS/FritzImageSegmentationDemo   where i can download .plist?

**Comment by FlorolF1** [comment]
Sry, it was my fault...
I have used Xcode Version 11.0. Updating to the newest version 11.2.1 fixed all errors in all my projects.
@SergeyDivak check documentation how to download and import .plist

Closing this issue

**Comment by GreydeskChirag** [comment]
Hey,

I have used Xcode Version 11.6. I am using Fritz its working fine.
Now i am trying to run in Xcode Version 12.0.
I am getting the error : Failed to build module 'FritzVisionHairSegmentationModelFast' from its module interface; the compiler that produced it, 'Apple Swift version 5.2 (swiftlang-1103.0.30 clang-1103.0.30)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'

Any idea how to fix this?

**Comment by jamesonthecrow** [comment]
> Hey,
> 
> I have used Xcode Version 11.6. I am using Fritz its working fine.
> Now i am trying to run in Xcode Version 12.0.
> I am getting the error : Failed to build module 'FritzVisionHairSegmentationModelFast' from its module interface; the compiler that produced it, 'Apple Swift version 5.2 (swiftlang-1103.0.30 clang-1103.0.30)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'
> 
> Any idea how to fix this?

You must upgrade to sdk version 6.0.0 to build with Xcode 12. In the future, please direct support questions to: https://support.fritz.ai
