### ISSUE TITLE
FritzVisionObjectModelFast inaccurate and slow compared to the previous version

### ISSUE THREAD

**Issue by florolf1** [fritzlabs/fritz-examples#38]
Hey,

i just updated my app to the new Fritz Version (5.0.1) and i noticed that the object detection is very slow (around 7 FPS, tested on iPhone X) and the bounding boxed are drawn at a wrong position.
I tested it with your FritAiStudio app and in my own app. The results are the same.

![IMG_1902](https://user-images.githubusercontent.com/29608141/72984553-42285a00-3de4-11ea-872d-132df6f5800d.png)

With the old ObjectDetectionModel i reached around 25 FPS and quite accurate bounding boxes. (Tested in my own app)

![IMG_1903](https://user-images.githubusercontent.com/29608141/72984610-65eba000-3de4-11ea-8071-47906c00770b.png)

Any ideas how to fix this?

**Comment by jamesonthecrow** [comment]
On the box positions, there is a bug in this line, where width is passed to the height dimension:

https://github.com/fritzlabs/fritz-examples/blob/master/iOS/FritzAIStudio/FritzAIStudio/Source/Modules/PredictorControllers/DetectObjects/DetectObjectsViewController.swift#L98

It should be:

`let rect = box.toCGRect(imgHeight: height, imgWidth: width, xOffset: 0.0, yOffset: yOffset)`

We'll be updating that example soon, but I'm still looking into the speed differences you brought up.

**Comment by jamesonthecrow** [comment]
Ok, the display bug should be fixed in this. The speed issue seems to be due the performance of Apple's non-max-suppression operator in Core ML. We'll look into replacing this or for an optimization in future versions, but it's unrelated to this repo so I'm going to close out for now.
