### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid output Tensor index: 2

### ISSUE THREAD

**Issue by nishchaljs** [fritzlabs/fritz-examples#50]
Hi,
I encounter this error when running the app which includes a custom tensorflowlite model I had trained for foot-keypoint-detection. Can you please help me resolve this??
The error points at **predictor = FritzVision.PoseEstimation.getPredictor(OnDeviceModel);**

![image](https://user-images.githubusercontent.com/43478373/89105304-98ceba80-d43d-11ea-8fde-1f79f8877a9c.png)

![image](https://user-images.githubusercontent.com/43478373/89105364-0f6bb800-d43e-11ea-99c3-0c00d44fcb0e.png)

**Comment by jamesonthecrow** [comment]
Please refer all questions to our support form: https://support.fritz.ai
